### ISSUE TITLE
DatabasesApiPlugin error

### ISSUE THREAD

**Issue by No1Evil** [timsixth/MinigameAPI#5]
Api version 1.1.0
I dont want to use database, however onEnable init migrations anyways.  Using also this:
```
@Override
    public PluginConfiguration configure() {
        return PluginConfiguration.builder()
                .tablesPrefix("game_")
                .useDataBase(false)
                .useDefaultStatsSystem(true)
                .arenaSaveType(ArenaSaveType.SINGLE_FILE)
                .build();
    }
```
Error:
```
"pl.timsixth.databasesapi.api.IDataBasesApi.getMigrations()" because the return value of "pl.timsixth.databasesapi.DatabasesApiPlugin.getApi()" is null
	at pl.timsixth.minigameapi.api.MiniGame.initMigrations(MiniGame.java:165) ~[?:?]
	at pl.timsixth.minigameapi.api.MiniGame.onEnable(MiniGame.java:91) ~[?:?]
	at org.oblivioncube.oblivionannihilation.OblivionAnnihilation.onEnable(OblivionAnnihilation.java:37) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:518) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:432) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at java.lang.Thread.run(Thread.java:842) [?:?]
```

**Comment by timsixth** [comment]
The useDataBase option doesn't disable every integration with the database. I will add the full support in a few days
